name: Typo checker

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check spelling of the entire repository
        uses: crate-ci/typos@v1.38.1
